name: Deployment Example
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize      
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Lint code
        run: npm run lint
      - name: Build code
        run: npm run build
      - name: Deploy
        run: |
          echo "Deploying to production..."
          echo "Deployed!"
